### PR TITLE
Update phantomjs version

### LINKED ISSUE #367: PhantomJS 2.0
I get errors on my website:

`'undefined' is not a function (evaluating 'n[i].bind(this)')`

I assume it is the same as this (tl;dr: Phantom 2.0 should work):
http://stackoverflow.com/questions/27634538/phantomjs-spiderable-meteor-up-issue

Could you update to 2.0 or add a version var?

### PR DESCRIPTION
**Pull request by nikhildaga**
fixes #367

### CODE REVIEW

**Comment by arunoda** [comment]
Have you tried using 2.0? Does it work. Earlier we had some issues working with it?

**Comment by nikhildaga** [comment]
@arunoda : Thanks for your reply. Can you tell me how to try on my mupx deployed server?

**Comment by arunoda** [comment]
There is a npm package called mupx install it. Checkout our mupx branch. It
has the all the docs you need.

**Comment by nikhildaga** [comment]
@arunoda : I already have installed and deployed using mupx. I want to know how to test whether phantomjs 2.0 works with mupx because with phantomjs 1.9 , I am facing problems. Thanks.

**Comment by nikhildaga** [comment]
In mupx, meteord takes care of phantomjs installation.  I have submitted a similar pull request in meteord.

**Comment by arunoda** [comment]
Okay you want to test that right ? Then try to to build meteord in your
server as meteorhacks:meteord

Then you can use your customized version?
